/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictoegame;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Zubair Akhtar
 */
public class TicToe extends javax.swing.JFrame {
    private int playerTurn = 1;
    private int winner = 0;
    private Color c;
    private int i=0;
    /**
     * Creates new form TicToe
     */
    
    private void winner(){
        if(one.getText()=="0" && four.getText()=="0" && seven.getText()=="0"){
           winner = 1;
        }else if(two.getText()=="0" && five.getText()=="0" && eight.getText()=="0"){
            winner = 1;
        }else if(three.getText()=="0" && six.getText()=="0" && nine.getText()=="0"){
            winner = 1;
        }else if(one.getText()=="0" && two.getText()=="0" && three.getText()=="0"){
            winner = 1;
        }else if(four.getText()=="0" && five.getText()=="0" && six.getText()=="0"){
            winner = 1;
        }else if(seven.getText()=="0" && eight.getText()=="0" && nine.getText()=="0"){
            winner = 1;
        }else if(one.getText()=="0" && five.getText()=="0" && nine.getText()=="0"){
            winner = 1;
        }else if(three.getText()=="0" && five.getText()=="0" && seven.getText()=="0"){
            winner = 1;
        }
        
        if(one.getText()=="X" && four.getText()=="X" && seven.getText()=="X"){
            winner = 2;
        }else if(two.getText()=="X" && five.getText()=="X" && eight.getText()=="X"){
            winner = 2;
        }else if(three.getText()=="X" && six.getText()=="X" && nine.getText()=="X"){
            winner = 2;
        }else if(one.getText()=="X" && two.getText()=="X" && three.getText()=="X"){
            winner = 2;
        }else if(four.getText()=="X" && five.getText()=="X" && six.getText()=="X"){
            winner = 2;
        }else if(seven.getText()=="X" && eight.getText()=="X" && nine.getText()=="X"){
            winner = 2;
        }else if(one.getText()=="X" && five.getText()=="X" && nine.getText()=="x"){
            winner = 2;
        }else if(three.getText()=="X" && five.getText()=="X" && seven.getText()=="X"){
            winner = 2;
        }
        if(i==9){
        lblTurn.setText("Draw");
        }else if(winner == 1){
            lblTurn.setText("Player 1 wins");
            JOptionPane.showMessageDialog(null, "Congratulations, Player 1 you are Winner");
        }else if(winner ==2){
            lblTurn.setText("Player 2 wins");
            JOptionPane.showMessageDialog(null, "Congratulations, Player 2 you are Winner");
        }
        
        
    }
    
    public TicToe() {
        initComponents();
        lblTurn.setText("Player 1 Turn");
        c = one.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        one = new javax.swing.JButton();
        three = new javax.swing.JButton();
        two = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        lblTurn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 90)); // NOI18N
        jLabel1.setText("Welcome to tic tac toe Game");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        one.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        three.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        two.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        four.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setFont(new java.awt.Font("AR BERKLEY", 1, 36)); // NOI18N
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(two, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(three, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTurn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTurn.setText("Player turn");

        jButton1.setFont(new java.awt.Font("Yu Mincho Demibold", 2, 18)); // NOI18N
        jButton1.setText("Click Here to Play Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        if(one.getText()!="0" && one.getText()!="X"){
            if(playerTurn==1){
                i++;
                one.setText("0");
                one.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();
            }else{
                i++;
                one.setText("X");
                one.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        if(two.getText()!="0" && two.getText()!="X"){
            if(playerTurn==1){
                i++;
                two.setText("0");
                two.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                two.setText("X");
                two.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        if(three.getText()!="0" && three.getText()!="X"){
            if(playerTurn==1){
                i++;
                three.setText("0");
                three.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                three.setText("X");
                three.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        if(four.getText()!="0" && four.getText()!="X"){
            if(playerTurn==1){
                i++;
                four.setText("0");
                four.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                four.setText("X");
                four.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        if(five.getText()!="0" && five.getText()!="X"){
            if(playerTurn==1){
                i++;
                five.setText("0");
                five.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                five.setText("X");
                five.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        if(six.getText()!="0" && six.getText()!="X"){
            if(playerTurn==1){
                i++;
                six.setText("0");
                six.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                six.setText("X");
                six.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        if(seven.getText()!="0" && seven.getText()!="X"){
            if(playerTurn==1){
                i++;
                seven.setText("0");
                seven.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                seven.setText("X");
                seven.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        if(eight.getText()!="0" && eight.getText()!="X"){
            if(playerTurn==1){
                i++;
                eight.setText("0");
                eight.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                eight.setText("X");
                eight.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        if(nine.getText()!="0" && nine.getText()!="X"){
            if(playerTurn==1){
                i++;
                nine.setText("0");
                nine.setBackground(Color.red);
                playerTurn=2;
                lblTurn.setText("Player 2 Turn");
                winner();

            }else{
                i++;
                nine.setText("X");
                nine.setBackground(Color.green);
                playerTurn=1;
                lblTurn.setText("Player 1 Turn");
                winner();
            }
        }else{
            JOptionPane.showMessageDialog(null, "You cannot choose this one");
        }
    }//GEN-LAST:event_nineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            lblTurn.setText("Player 1 Turn");
            playerTurn = 1;
            winner=0;
            i=0;
            one.setBackground(c);
            two.setBackground(c);
            three.setBackground(c);
            four.setBackground(c);
            five.setBackground(c);
            six.setBackground(c);
            seven.setBackground(c);
            eight.setBackground(c);
            nine.setBackground(c);
            one.setText(null);
            two.setText(null);
            three.setText(null);
            four.setText(null);
            five.setText(null);
            six.setText(null);
            seven.setText(null);
            eight.setText(null);
            nine.setText(null);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
